services:
  postgres:
    image: postgres:16
    container_name: mealvote-postgres
    environment:
      POSTGRES_DB: mealvote
      POSTGRES_USER: mealvote
      POSTGRES_PASSWORD: mealvote
    ports:
      - "5432:5432"
    volumes:
      - mealvote-postgres:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: mealvote-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env.deployment
    environment:
      - HTTP_ADDR=:8080
      - DATABASE_URL=postgres://mealvote:mealvote@postgres:5432/mealvote?sslmode=disable
      - DB_AUTOMIGRATE=true
      - RATE_LIMIT_LOGIN_MAX=0
      - RATE_LIMIT_REGISTER_MAX=0
      - CHAIN_ID=11155111
      - GOVERNANCE_CONTRACT_ADDRESS=0xe4FBAD988f520648dd47518283Ac06bE326a1105
      - ORDER_ESCROW_CONTRACT_ADDRESS=0xc14d75D6f2AdBEA94caBeC83CD508D9c61FDe2ce
      - ORDER_CONTRACT_ADDRESS=0xc14d75D6f2AdBEA94caBeC83CD508D9c61FDe2ce
      - PLATFORM_TREASURY_ADDRESS=0x4A996A04cDF63dAbda75A0aeaA12ca837E00e1ec
      - RPC_URL=https://eth-sepolia.g.alchemy.com/v2/74uXRzkYdgy_YGCHwKsSJ
      - MEMBERSHIP_TOKEN_ADDRESS=0xf3C81afF0845dc39fcE188d7b6CFDb9b5f2aB100
    depends_on:
      - postgres

  frontend:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.dev
    container_name: mealvote-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8080
    depends_on:
      - backend

volumes:
  mealvote-postgres:
